-- MySQL Script generated by MySQL Workbench
-- Wed Feb  2 12:49:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema offline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema offline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `offline` DEFAULT CHARACTER SET utf8mb4 ;
USE `offline` ;

-- -----------------------------------------------------
-- Table `offline`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `mobile` CHAR(12) NULL,
  `role` ENUM('super admin', 'admin', 'seller', 'user') NULL DEFAULT 'user',
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  INDEX `fk_users_created_by_idx` (`created_by` ASC) ,
  CONSTRAINT `fk_users_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_table1_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_table1_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `price` DECIMAL(8,2) NULL,
  `qty` INT NULL,
  `offer_price` DECIMAL(8,2) NULL,
  `category_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  INDEX `fk_categories_has_brands_brands1_idx` (`brand_id` ASC) ,
  INDEX `fk_categories_has_brands_categories1_idx` (`category_id` ASC) ,
  PRIMARY KEY (`id`),
  INDEX `fk_products_users1_idx` (`seller_id` ASC) ,
  CONSTRAINT `fk_categories_has_brands_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `offline`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categories_has_brands_brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `offline`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_users1`
    FOREIGN KEY (`seller_id`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_images_products1_idx` (`products_id` ASC) ,
  CONSTRAINT `fk_product_images_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `offline`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`contacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contact` VARCHAR(255) NULL,
  `type` ENUM('address', 'mobile') NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NULL DEFAULT current_timestamp,
  `created_by` INT NOT NULL,
  `address_id` INT NOT NULL,
  `total` DECIMAL(9,2) NULL,
  `payment_method` ENUM('cash', 'visa') NULL,
  `shipping_fees` DECIMAL(8,2) NULL,
  `status` ENUM('pending', 'rejected', 'approved', 'shipped', 'delivered', 'refund') NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`created_by` ASC) ,
  INDEX `fk_orders_contacts1_idx` (`address_id` ASC) ,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `offline`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_contacts1`
    FOREIGN KEY (`address_id`)
    REFERENCES `offline`.`contacts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offline`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offline`.`order_items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `qty` INT NULL,
  `unit_price` DECIMAL(8,2) NULL,
  `review` TINYINT NULL COMMENT 'from 1 to 5',
  PRIMARY KEY (`id`),
  INDEX `fk_order_items_orders1_idx` (`order_id` ASC) ,
  INDEX `fk_order_items_products1_idx` (`product_id` ASC) ,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `offline`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `offline`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
