1)
create table MY_EMPLOYEE(
    ID INTEGER NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    USERID VARCHAR(8),
    SALARY DECIMAL(8,2)
);

2)
INSERT INTO MY_EMPLOYEE VALUE(1, 'Patel', 'Ralph', 'rpatel', 895);
INSERT INTO MY_EMPLOYEE VALUE(2, 'Dancs', 'Dancs', 'Dancs', 860);
INSERT INTO MY_EMPLOYEE VALUE(3, 'Biri', 'Ben', 'bbiri', 1100);
INSERT INTO MY_EMPLOYEE VALUE(4, 'Newman', 'Chad', 'cnewman', 750);
INSERT INTO MY_EMPLOYEE VALUE(5, 'Ropeburn', 'Audrey', 'aropebur', 1550);


3)
UPDATE MY_EMPLOYEE SET LAST_NAME = 'Drexler' WHERE ID = 3;

4)
UPDATE MY_EMPLOYEE SET SALARY = 1000 WHERE SALARY < 900;

5)
DELETE FROM MY_EMPLOYEE WHERE LAST_NAME = 'Dancs' AND FIRST_NAME = 'Betty';


6)
use hr;
create table DEPT(
    ID INTEGER(7) NOT NULL PRIMARY KEY,
    NAME VARCHAR(25)
);

7)
INSERT INTO DEPT SELECT DEPARTMENT_ID , DEPARTMENT_NAME FROM
DEPARTMENTS;

8)
CREATE TABLE EMP(
    ID INTEGER(7) NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(25),
    FIRST_NAME VARCHAR(25),
    DEPT_ID INTEGER(7)
);

9)INSERT INTO EMP SELECT EMPLOYEE_ID, LAST_NAME, FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES;

10) 
DROP TABLE EMP;
DROP TABLE DEPT;

create table if not exists EMP as  select EMPLOYEE_ID as "emp_id" from EMPLOYEES;